#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fitness
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="FitnessNutritieDB")]
	public partial class FitnessDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertExercitii(Exercitii instance);
    partial void UpdateExercitii(Exercitii instance);
    partial void DeleteExercitii(Exercitii instance);
    partial void InsertIstoricAntrenamente(IstoricAntrenamente instance);
    partial void UpdateIstoricAntrenamente(IstoricAntrenamente instance);
    partial void DeleteIstoricAntrenamente(IstoricAntrenamente instance);
    partial void InsertIstoricGreutate(IstoricGreutate instance);
    partial void UpdateIstoricGreutate(IstoricGreutate instance);
    partial void DeleteIstoricGreutate(IstoricGreutate instance);
    partial void InsertPlanAlimentarIstoric(PlanAlimentarIstoric instance);
    partial void UpdatePlanAlimentarIstoric(PlanAlimentarIstoric instance);
    partial void DeletePlanAlimentarIstoric(PlanAlimentarIstoric instance);
    partial void InsertUtilizatori(Utilizatori instance);
    partial void UpdateUtilizatori(Utilizatori instance);
    partial void DeleteUtilizatori(Utilizatori instance);
    partial void InsertRetete(Retete instance);
    partial void UpdateRetete(Retete instance);
    partial void DeleteRetete(Retete instance);
    #endregion
		
		public FitnessDBDataContext() : 
				base(global::Fitness.Properties.Settings.Default.FitnessNutritieDBConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public FitnessDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public FitnessDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public FitnessDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public FitnessDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Exercitii> Exercitiis
		{
			get
			{
				return this.GetTable<Exercitii>();
			}
		}
		
		public System.Data.Linq.Table<IstoricAntrenamente> IstoricAntrenamentes
		{
			get
			{
				return this.GetTable<IstoricAntrenamente>();
			}
		}
		
		public System.Data.Linq.Table<IstoricGreutate> IstoricGreutates
		{
			get
			{
				return this.GetTable<IstoricGreutate>();
			}
		}
		
		public System.Data.Linq.Table<PlanAlimentarIstoric> PlanAlimentarIstorics
		{
			get
			{
				return this.GetTable<PlanAlimentarIstoric>();
			}
		}
		
		public System.Data.Linq.Table<Utilizatori> Utilizatoris
		{
			get
			{
				return this.GetTable<Utilizatori>();
			}
		}
		
		public System.Data.Linq.Table<Retete> Retetes
		{
			get
			{
				return this.GetTable<Retete>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Exercitii")]
	public partial class Exercitii : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _DenumireExercitiu;
		
		private System.Nullable<int> _Repetari;
		
		private string _GrupaMusculara;
		
		private System.Nullable<int> _Seturi;
		
		private string _Descriere;
		
		private System.Nullable<int> _TimpEstimareExecutie;
		
		private EntitySet<IstoricAntrenamente> _IstoricAntrenamentes;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnDenumireExercitiuChanging(string value);
    partial void OnDenumireExercitiuChanged();
    partial void OnRepetariChanging(System.Nullable<int> value);
    partial void OnRepetariChanged();
    partial void OnGrupaMuscularaChanging(string value);
    partial void OnGrupaMuscularaChanged();
    partial void OnSeturiChanging(System.Nullable<int> value);
    partial void OnSeturiChanged();
    partial void OnDescriereChanging(string value);
    partial void OnDescriereChanged();
    partial void OnTimpEstimareExecutieChanging(System.Nullable<int> value);
    partial void OnTimpEstimareExecutieChanged();
    #endregion
		
		public Exercitii()
		{
			this._IstoricAntrenamentes = new EntitySet<IstoricAntrenamente>(new Action<IstoricAntrenamente>(this.attach_IstoricAntrenamentes), new Action<IstoricAntrenamente>(this.detach_IstoricAntrenamentes));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DenumireExercitiu", DbType="NVarChar(100)")]
		public string DenumireExercitiu
		{
			get
			{
				return this._DenumireExercitiu;
			}
			set
			{
				if ((this._DenumireExercitiu != value))
				{
					this.OnDenumireExercitiuChanging(value);
					this.SendPropertyChanging();
					this._DenumireExercitiu = value;
					this.SendPropertyChanged("DenumireExercitiu");
					this.OnDenumireExercitiuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Repetari", DbType="Int")]
		public System.Nullable<int> Repetari
		{
			get
			{
				return this._Repetari;
			}
			set
			{
				if ((this._Repetari != value))
				{
					this.OnRepetariChanging(value);
					this.SendPropertyChanging();
					this._Repetari = value;
					this.SendPropertyChanged("Repetari");
					this.OnRepetariChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GrupaMusculara", DbType="NVarChar(100)")]
		public string GrupaMusculara
		{
			get
			{
				return this._GrupaMusculara;
			}
			set
			{
				if ((this._GrupaMusculara != value))
				{
					this.OnGrupaMuscularaChanging(value);
					this.SendPropertyChanging();
					this._GrupaMusculara = value;
					this.SendPropertyChanged("GrupaMusculara");
					this.OnGrupaMuscularaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Seturi", DbType="Int")]
		public System.Nullable<int> Seturi
		{
			get
			{
				return this._Seturi;
			}
			set
			{
				if ((this._Seturi != value))
				{
					this.OnSeturiChanging(value);
					this.SendPropertyChanging();
					this._Seturi = value;
					this.SendPropertyChanged("Seturi");
					this.OnSeturiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descriere", DbType="NVarChar(100)")]
		public string Descriere
		{
			get
			{
				return this._Descriere;
			}
			set
			{
				if ((this._Descriere != value))
				{
					this.OnDescriereChanging(value);
					this.SendPropertyChanging();
					this._Descriere = value;
					this.SendPropertyChanged("Descriere");
					this.OnDescriereChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimpEstimareExecutie", DbType="Int")]
		public System.Nullable<int> TimpEstimareExecutie
		{
			get
			{
				return this._TimpEstimareExecutie;
			}
			set
			{
				if ((this._TimpEstimareExecutie != value))
				{
					this.OnTimpEstimareExecutieChanging(value);
					this.SendPropertyChanging();
					this._TimpEstimareExecutie = value;
					this.SendPropertyChanged("TimpEstimareExecutie");
					this.OnTimpEstimareExecutieChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Exercitii_IstoricAntrenamente", Storage="_IstoricAntrenamentes", ThisKey="ID", OtherKey="ExercitiuID")]
		public EntitySet<IstoricAntrenamente> IstoricAntrenamentes
		{
			get
			{
				return this._IstoricAntrenamentes;
			}
			set
			{
				this._IstoricAntrenamentes.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_IstoricAntrenamentes(IstoricAntrenamente entity)
		{
			this.SendPropertyChanging();
			entity.Exercitii = this;
		}
		
		private void detach_IstoricAntrenamentes(IstoricAntrenamente entity)
		{
			this.SendPropertyChanging();
			entity.Exercitii = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.IstoricAntrenamente")]
	public partial class IstoricAntrenamente : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private int _UserID;
		
		private int _ExercitiuID;
		
		private System.DateTime _DataExecutie;
		
		private System.TimeSpan _OraExecutie;
		
		private EntityRef<Exercitii> _Exercitii;
		
		private EntityRef<Utilizatori> _Utilizatori;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnUserIDChanging(int value);
    partial void OnUserIDChanged();
    partial void OnExercitiuIDChanging(int value);
    partial void OnExercitiuIDChanged();
    partial void OnDataExecutieChanging(System.DateTime value);
    partial void OnDataExecutieChanged();
    partial void OnOraExecutieChanging(System.TimeSpan value);
    partial void OnOraExecutieChanged();
    #endregion
		
		public IstoricAntrenamente()
		{
			this._Exercitii = default(EntityRef<Exercitii>);
			this._Utilizatori = default(EntityRef<Utilizatori>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="Int NOT NULL")]
		public int UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					if (this._Utilizatori.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUserIDChanging(value);
					this.SendPropertyChanging();
					this._UserID = value;
					this.SendPropertyChanged("UserID");
					this.OnUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExercitiuID", DbType="Int NOT NULL")]
		public int ExercitiuID
		{
			get
			{
				return this._ExercitiuID;
			}
			set
			{
				if ((this._ExercitiuID != value))
				{
					if (this._Exercitii.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnExercitiuIDChanging(value);
					this.SendPropertyChanging();
					this._ExercitiuID = value;
					this.SendPropertyChanged("ExercitiuID");
					this.OnExercitiuIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataExecutie", DbType="Date NOT NULL")]
		public System.DateTime DataExecutie
		{
			get
			{
				return this._DataExecutie;
			}
			set
			{
				if ((this._DataExecutie != value))
				{
					this.OnDataExecutieChanging(value);
					this.SendPropertyChanging();
					this._DataExecutie = value;
					this.SendPropertyChanged("DataExecutie");
					this.OnDataExecutieChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OraExecutie", DbType="Time NOT NULL")]
		public System.TimeSpan OraExecutie
		{
			get
			{
				return this._OraExecutie;
			}
			set
			{
				if ((this._OraExecutie != value))
				{
					this.OnOraExecutieChanging(value);
					this.SendPropertyChanging();
					this._OraExecutie = value;
					this.SendPropertyChanged("OraExecutie");
					this.OnOraExecutieChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Exercitii_IstoricAntrenamente", Storage="_Exercitii", ThisKey="ExercitiuID", OtherKey="ID", IsForeignKey=true)]
		public Exercitii Exercitii
		{
			get
			{
				return this._Exercitii.Entity;
			}
			set
			{
				Exercitii previousValue = this._Exercitii.Entity;
				if (((previousValue != value) 
							|| (this._Exercitii.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Exercitii.Entity = null;
						previousValue.IstoricAntrenamentes.Remove(this);
					}
					this._Exercitii.Entity = value;
					if ((value != null))
					{
						value.IstoricAntrenamentes.Add(this);
						this._ExercitiuID = value.ID;
					}
					else
					{
						this._ExercitiuID = default(int);
					}
					this.SendPropertyChanged("Exercitii");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Utilizatori_IstoricAntrenamente", Storage="_Utilizatori", ThisKey="UserID", OtherKey="ID", IsForeignKey=true)]
		public Utilizatori Utilizatori
		{
			get
			{
				return this._Utilizatori.Entity;
			}
			set
			{
				Utilizatori previousValue = this._Utilizatori.Entity;
				if (((previousValue != value) 
							|| (this._Utilizatori.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Utilizatori.Entity = null;
						previousValue.IstoricAntrenamentes.Remove(this);
					}
					this._Utilizatori.Entity = value;
					if ((value != null))
					{
						value.IstoricAntrenamentes.Add(this);
						this._UserID = value.ID;
					}
					else
					{
						this._UserID = default(int);
					}
					this.SendPropertyChanged("Utilizatori");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.IstoricGreutate")]
	public partial class IstoricGreutate : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private int _UserID;
		
		private System.DateTime _Data;
		
		private decimal _Greutate;
		
		private EntityRef<Utilizatori> _Utilizatori;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnUserIDChanging(int value);
    partial void OnUserIDChanged();
    partial void OnDataChanging(System.DateTime value);
    partial void OnDataChanged();
    partial void OnGreutateChanging(decimal value);
    partial void OnGreutateChanged();
    #endregion
		
		public IstoricGreutate()
		{
			this._Utilizatori = default(EntityRef<Utilizatori>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="Int NOT NULL")]
		public int UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					if (this._Utilizatori.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUserIDChanging(value);
					this.SendPropertyChanging();
					this._UserID = value;
					this.SendPropertyChanged("UserID");
					this.OnUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Data", DbType="Date NOT NULL")]
		public System.DateTime Data
		{
			get
			{
				return this._Data;
			}
			set
			{
				if ((this._Data != value))
				{
					this.OnDataChanging(value);
					this.SendPropertyChanging();
					this._Data = value;
					this.SendPropertyChanged("Data");
					this.OnDataChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Greutate", DbType="Decimal(5,2) NOT NULL")]
		public decimal Greutate
		{
			get
			{
				return this._Greutate;
			}
			set
			{
				if ((this._Greutate != value))
				{
					this.OnGreutateChanging(value);
					this.SendPropertyChanging();
					this._Greutate = value;
					this.SendPropertyChanged("Greutate");
					this.OnGreutateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Utilizatori_IstoricGreutate", Storage="_Utilizatori", ThisKey="UserID", OtherKey="ID", IsForeignKey=true)]
		public Utilizatori Utilizatori
		{
			get
			{
				return this._Utilizatori.Entity;
			}
			set
			{
				Utilizatori previousValue = this._Utilizatori.Entity;
				if (((previousValue != value) 
							|| (this._Utilizatori.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Utilizatori.Entity = null;
						previousValue.IstoricGreutates.Remove(this);
					}
					this._Utilizatori.Entity = value;
					if ((value != null))
					{
						value.IstoricGreutates.Add(this);
						this._UserID = value.ID;
					}
					else
					{
						this._UserID = default(int);
					}
					this.SendPropertyChanged("Utilizatori");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PlanAlimentarIstoric")]
	public partial class PlanAlimentarIstoric : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private int _UserID;
		
		private int _RetetaID;
		
		private System.DateTime _Data;
		
		private string _TipMasa;
		
		private EntityRef<Utilizatori> _Utilizatori;
		
		private EntityRef<Retete> _Retete;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnUserIDChanging(int value);
    partial void OnUserIDChanged();
    partial void OnRetetaIDChanging(int value);
    partial void OnRetetaIDChanged();
    partial void OnDataChanging(System.DateTime value);
    partial void OnDataChanged();
    partial void OnTipMasaChanging(string value);
    partial void OnTipMasaChanged();
    #endregion
		
		public PlanAlimentarIstoric()
		{
			this._Utilizatori = default(EntityRef<Utilizatori>);
			this._Retete = default(EntityRef<Retete>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="Int NOT NULL")]
		public int UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					if (this._Utilizatori.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUserIDChanging(value);
					this.SendPropertyChanging();
					this._UserID = value;
					this.SendPropertyChanged("UserID");
					this.OnUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RetetaID", DbType="Int NOT NULL")]
		public int RetetaID
		{
			get
			{
				return this._RetetaID;
			}
			set
			{
				if ((this._RetetaID != value))
				{
					if (this._Retete.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnRetetaIDChanging(value);
					this.SendPropertyChanging();
					this._RetetaID = value;
					this.SendPropertyChanged("RetetaID");
					this.OnRetetaIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Data", DbType="Date NOT NULL")]
		public System.DateTime Data
		{
			get
			{
				return this._Data;
			}
			set
			{
				if ((this._Data != value))
				{
					this.OnDataChanging(value);
					this.SendPropertyChanging();
					this._Data = value;
					this.SendPropertyChanged("Data");
					this.OnDataChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipMasa", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string TipMasa
		{
			get
			{
				return this._TipMasa;
			}
			set
			{
				if ((this._TipMasa != value))
				{
					this.OnTipMasaChanging(value);
					this.SendPropertyChanging();
					this._TipMasa = value;
					this.SendPropertyChanged("TipMasa");
					this.OnTipMasaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Utilizatori_PlanAlimentarIstoric", Storage="_Utilizatori", ThisKey="UserID", OtherKey="ID", IsForeignKey=true)]
		public Utilizatori Utilizatori
		{
			get
			{
				return this._Utilizatori.Entity;
			}
			set
			{
				Utilizatori previousValue = this._Utilizatori.Entity;
				if (((previousValue != value) 
							|| (this._Utilizatori.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Utilizatori.Entity = null;
						previousValue.PlanAlimentarIstorics.Remove(this);
					}
					this._Utilizatori.Entity = value;
					if ((value != null))
					{
						value.PlanAlimentarIstorics.Add(this);
						this._UserID = value.ID;
					}
					else
					{
						this._UserID = default(int);
					}
					this.SendPropertyChanged("Utilizatori");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Retete1_PlanAlimentarIstoric", Storage="_Retete", ThisKey="RetetaID", OtherKey="ID", IsForeignKey=true)]
		public Retete Retete
		{
			get
			{
				return this._Retete.Entity;
			}
			set
			{
				Retete previousValue = this._Retete.Entity;
				if (((previousValue != value) 
							|| (this._Retete.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Retete.Entity = null;
						previousValue.PlanAlimentarIstorics.Remove(this);
					}
					this._Retete.Entity = value;
					if ((value != null))
					{
						value.PlanAlimentarIstorics.Add(this);
						this._RetetaID = value.ID;
					}
					else
					{
						this._RetetaID = default(int);
					}
					this.SendPropertyChanged("Retete");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Utilizatori")]
	public partial class Utilizatori : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Name;
		
		private string _HashedPassword;
		
		private string _Sex;
		
		private System.Nullable<decimal> _Height;
		
		private System.Nullable<decimal> _Kilograms;
		
		private string _PhysicalCondition;
		
		private string _UserType;
		
		private EntitySet<IstoricAntrenamente> _IstoricAntrenamentes;
		
		private EntitySet<IstoricGreutate> _IstoricGreutates;
		
		private EntitySet<PlanAlimentarIstoric> _PlanAlimentarIstorics;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnHashedPasswordChanging(string value);
    partial void OnHashedPasswordChanged();
    partial void OnSexChanging(string value);
    partial void OnSexChanged();
    partial void OnHeightChanging(System.Nullable<decimal> value);
    partial void OnHeightChanged();
    partial void OnKilogramsChanging(System.Nullable<decimal> value);
    partial void OnKilogramsChanged();
    partial void OnPhysicalConditionChanging(string value);
    partial void OnPhysicalConditionChanged();
    partial void OnUserTypeChanging(string value);
    partial void OnUserTypeChanged();
    #endregion
		
		public Utilizatori()
		{
			this._IstoricAntrenamentes = new EntitySet<IstoricAntrenamente>(new Action<IstoricAntrenamente>(this.attach_IstoricAntrenamentes), new Action<IstoricAntrenamente>(this.detach_IstoricAntrenamentes));
			this._IstoricGreutates = new EntitySet<IstoricGreutate>(new Action<IstoricGreutate>(this.attach_IstoricGreutates), new Action<IstoricGreutate>(this.detach_IstoricGreutates));
			this._PlanAlimentarIstorics = new EntitySet<PlanAlimentarIstoric>(new Action<PlanAlimentarIstoric>(this.attach_PlanAlimentarIstorics), new Action<PlanAlimentarIstoric>(this.detach_PlanAlimentarIstorics));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HashedPassword", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string HashedPassword
		{
			get
			{
				return this._HashedPassword;
			}
			set
			{
				if ((this._HashedPassword != value))
				{
					this.OnHashedPasswordChanging(value);
					this.SendPropertyChanging();
					this._HashedPassword = value;
					this.SendPropertyChanged("HashedPassword");
					this.OnHashedPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sex", DbType="NVarChar(16)")]
		public string Sex
		{
			get
			{
				return this._Sex;
			}
			set
			{
				if ((this._Sex != value))
				{
					this.OnSexChanging(value);
					this.SendPropertyChanging();
					this._Sex = value;
					this.SendPropertyChanged("Sex");
					this.OnSexChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Height", DbType="Decimal(5,2)")]
		public System.Nullable<decimal> Height
		{
			get
			{
				return this._Height;
			}
			set
			{
				if ((this._Height != value))
				{
					this.OnHeightChanging(value);
					this.SendPropertyChanging();
					this._Height = value;
					this.SendPropertyChanged("Height");
					this.OnHeightChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kilograms", DbType="Decimal(5,2)")]
		public System.Nullable<decimal> Kilograms
		{
			get
			{
				return this._Kilograms;
			}
			set
			{
				if ((this._Kilograms != value))
				{
					this.OnKilogramsChanging(value);
					this.SendPropertyChanging();
					this._Kilograms = value;
					this.SendPropertyChanged("Kilograms");
					this.OnKilogramsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhysicalCondition", DbType="NVarChar(50)")]
		public string PhysicalCondition
		{
			get
			{
				return this._PhysicalCondition;
			}
			set
			{
				if ((this._PhysicalCondition != value))
				{
					this.OnPhysicalConditionChanging(value);
					this.SendPropertyChanging();
					this._PhysicalCondition = value;
					this.SendPropertyChanged("PhysicalCondition");
					this.OnPhysicalConditionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserType", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string UserType
		{
			get
			{
				return this._UserType;
			}
			set
			{
				if ((this._UserType != value))
				{
					this.OnUserTypeChanging(value);
					this.SendPropertyChanging();
					this._UserType = value;
					this.SendPropertyChanged("UserType");
					this.OnUserTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Utilizatori_IstoricAntrenamente", Storage="_IstoricAntrenamentes", ThisKey="ID", OtherKey="UserID")]
		public EntitySet<IstoricAntrenamente> IstoricAntrenamentes
		{
			get
			{
				return this._IstoricAntrenamentes;
			}
			set
			{
				this._IstoricAntrenamentes.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Utilizatori_IstoricGreutate", Storage="_IstoricGreutates", ThisKey="ID", OtherKey="UserID")]
		public EntitySet<IstoricGreutate> IstoricGreutates
		{
			get
			{
				return this._IstoricGreutates;
			}
			set
			{
				this._IstoricGreutates.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Utilizatori_PlanAlimentarIstoric", Storage="_PlanAlimentarIstorics", ThisKey="ID", OtherKey="UserID")]
		public EntitySet<PlanAlimentarIstoric> PlanAlimentarIstorics
		{
			get
			{
				return this._PlanAlimentarIstorics;
			}
			set
			{
				this._PlanAlimentarIstorics.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_IstoricAntrenamentes(IstoricAntrenamente entity)
		{
			this.SendPropertyChanging();
			entity.Utilizatori = this;
		}
		
		private void detach_IstoricAntrenamentes(IstoricAntrenamente entity)
		{
			this.SendPropertyChanging();
			entity.Utilizatori = null;
		}
		
		private void attach_IstoricGreutates(IstoricGreutate entity)
		{
			this.SendPropertyChanging();
			entity.Utilizatori = this;
		}
		
		private void detach_IstoricGreutates(IstoricGreutate entity)
		{
			this.SendPropertyChanging();
			entity.Utilizatori = null;
		}
		
		private void attach_PlanAlimentarIstorics(PlanAlimentarIstoric entity)
		{
			this.SendPropertyChanging();
			entity.Utilizatori = this;
		}
		
		private void detach_PlanAlimentarIstorics(PlanAlimentarIstoric entity)
		{
			this.SendPropertyChanging();
			entity.Utilizatori = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Retete")]
	public partial class Retete : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private int _Calorii;
		
		private decimal _Carbohidrati;
		
		private decimal _Proteine;
		
		private decimal _Grasimi;
		
		private string _Nume;
		
		private string _Ingrediente;
		
		private string _TipMasa;
		
		private EntitySet<PlanAlimentarIstoric> _PlanAlimentarIstorics;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnCaloriiChanging(int value);
    partial void OnCaloriiChanged();
    partial void OnCarbohidratiChanging(decimal value);
    partial void OnCarbohidratiChanged();
    partial void OnProteineChanging(decimal value);
    partial void OnProteineChanged();
    partial void OnGrasimiChanging(decimal value);
    partial void OnGrasimiChanged();
    partial void OnNumeChanging(string value);
    partial void OnNumeChanged();
    partial void OnIngredienteChanging(string value);
    partial void OnIngredienteChanged();
    partial void OnTipMasaChanging(string value);
    partial void OnTipMasaChanged();
    #endregion
		
		public Retete()
		{
			this._PlanAlimentarIstorics = new EntitySet<PlanAlimentarIstoric>(new Action<PlanAlimentarIstoric>(this.attach_PlanAlimentarIstorics), new Action<PlanAlimentarIstoric>(this.detach_PlanAlimentarIstorics));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Calorii", DbType="Int NOT NULL")]
		public int Calorii
		{
			get
			{
				return this._Calorii;
			}
			set
			{
				if ((this._Calorii != value))
				{
					this.OnCaloriiChanging(value);
					this.SendPropertyChanging();
					this._Calorii = value;
					this.SendPropertyChanged("Calorii");
					this.OnCaloriiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Carbohidrati", DbType="Decimal(5,2) NOT NULL")]
		public decimal Carbohidrati
		{
			get
			{
				return this._Carbohidrati;
			}
			set
			{
				if ((this._Carbohidrati != value))
				{
					this.OnCarbohidratiChanging(value);
					this.SendPropertyChanging();
					this._Carbohidrati = value;
					this.SendPropertyChanged("Carbohidrati");
					this.OnCarbohidratiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Proteine", DbType="Decimal(5,2) NOT NULL")]
		public decimal Proteine
		{
			get
			{
				return this._Proteine;
			}
			set
			{
				if ((this._Proteine != value))
				{
					this.OnProteineChanging(value);
					this.SendPropertyChanging();
					this._Proteine = value;
					this.SendPropertyChanged("Proteine");
					this.OnProteineChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Grasimi", DbType="Decimal(5,2) NOT NULL")]
		public decimal Grasimi
		{
			get
			{
				return this._Grasimi;
			}
			set
			{
				if ((this._Grasimi != value))
				{
					this.OnGrasimiChanging(value);
					this.SendPropertyChanging();
					this._Grasimi = value;
					this.SendPropertyChanged("Grasimi");
					this.OnGrasimiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nume", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string Nume
		{
			get
			{
				return this._Nume;
			}
			set
			{
				if ((this._Nume != value))
				{
					this.OnNumeChanging(value);
					this.SendPropertyChanging();
					this._Nume = value;
					this.SendPropertyChanged("Nume");
					this.OnNumeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ingrediente", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Ingrediente
		{
			get
			{
				return this._Ingrediente;
			}
			set
			{
				if ((this._Ingrediente != value))
				{
					this.OnIngredienteChanging(value);
					this.SendPropertyChanging();
					this._Ingrediente = value;
					this.SendPropertyChanged("Ingrediente");
					this.OnIngredienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipMasa", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string TipMasa
		{
			get
			{
				return this._TipMasa;
			}
			set
			{
				if ((this._TipMasa != value))
				{
					this.OnTipMasaChanging(value);
					this.SendPropertyChanging();
					this._TipMasa = value;
					this.SendPropertyChanged("TipMasa");
					this.OnTipMasaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Retete1_PlanAlimentarIstoric", Storage="_PlanAlimentarIstorics", ThisKey="ID", OtherKey="RetetaID")]
		public EntitySet<PlanAlimentarIstoric> PlanAlimentarIstorics
		{
			get
			{
				return this._PlanAlimentarIstorics;
			}
			set
			{
				this._PlanAlimentarIstorics.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PlanAlimentarIstorics(PlanAlimentarIstoric entity)
		{
			this.SendPropertyChanging();
			entity.Retete = this;
		}
		
		private void detach_PlanAlimentarIstorics(PlanAlimentarIstoric entity)
		{
			this.SendPropertyChanging();
			entity.Retete = null;
		}
	}
}
#pragma warning restore 1591
